# Email Configuration
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.username=luxuryhotel999@gmail.com
email.password=ycby ivph hzcf jnqa
email.from.name=Luxury Hotel
email.reply.to=noreply@luxuryhotel.com

# Email Security
email.enable.ssl=true
email.enable.tls=true
email.trust.host=true